version: "2"
services:
  my-wp:
    image: wordpress
    volumes:
      - .:/var/www/html/wp-content/themes/Shanken-News-Daily
    ports:
      - "8093:80"
    environment:
      WORDPRESS_DB_PASSWORD: 'admin'
      WORDPRESS_DB_USER: 'admin'
      WORDPRESS_DB_HOST: 'whiskynew.chqvualwh4wy.us-east-1.rds.amazonaws.com'
      WORDPRESS_DB_NAME: 'wp_snd_local'
